# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Croc < Formula
  desc "croc is a tool that allows any two computers to simply and securely transfer files and folders."
  homepage "https://schollz.com/software/croc/"
  version "9.5.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/schollz/croc/releases/download/v9.5.6/croc_9.5.6_macOS-64bit.tar.gz"
      sha256 "4387ea3a3bb91d19191101dda89e35e364aa6d32462b6507f3fd2a45e0d1a7ef"
    end
    if Hardware::CPU.arm?
      url "https://github.com/schollz/croc/releases/download/v9.5.6/croc_9.5.6_macOS-ARM64.tar.gz"
      sha256 "630453e6d78095ee6d865737a44ed963619ce57880f7fe674d235a835aab1b6b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/schollz/croc/releases/download/v9.5.6/croc_9.5.6_Linux-64bit.tar.gz"
      sha256 "87938b8ec19ecbebe6c9500258823f5e71cbb5487cdb9bc19327edad8ef45003"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schollz/croc/releases/download/v9.5.6/croc_9.5.6_Linux-ARM64.tar.gz"
      sha256 "9990b1fee16f46e94a833301e1c05e6535cb731e07ac533828437005c9536f0e"
    end
  end

  def install
    bin.install "croc"
  end

  test do
    system "#{bin}/croc --version"
  end
end
