# This file was generated by GoReleaser. DO NOT EDIT.
class Hostyoself < Formula
  desc "hostyoself lets you host your files using websockets from the command line or a browser."
  homepage "https://schollz.com/software/hostyoself/"
  url "https://github.com/schollz/hostyoself/releases/download/v0.0.1/hostyoself_0.0.1_macOS-64bit.tar.gz"
  version "0.0.1"
  sha256 "45572592fe09ffaabd6defc8ab06b0970287a6c3ac5e95756b9e9e81dc4a3927"

  def install
    bin.install "hostyoself"
  end

  test do
    system "#{bin}/hostyoself --version"
  end
end
