# This file was generated by GoReleaser. DO NOT EDIT.
class Ingredients < Formula
  desc "ingredients is a tool that allows any two computers to simply and securely transfer files and folders."
  homepage "https://schollz.com/blog/ingredients/"
  url "https://github.com/schollz/ingredients/releases/download/v0.1.4/ingredients_0.1.4_macOS-64bit.tar.gz"
  version "0.1.4"
  sha256 "0d54e5e83b0b5b6b5dc8cf458978e6bc2851d69b8e09e444c0f73cf710813315"

  def install
    bin.install "ingredients"
  end

  test do
    system "#{bin}/ingredients --version"
  end
end
