# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seamlessloop < Formula
  desc "seamlessloop is a tool to make seamless loops (requires sox)."
  homepage "https://schollz.com/software/seamlessloop/"
  version "0.1.0"

  on_macos do
    url "https://github.com/schollz/seamlessloop/releases/download/v0.1.0/seamlessloop_0.1.0_macOS-64bit.tar.gz"
    sha256 "e81642b158ecfb8dbe084869ce53410e7bafb4fcd5cb2acd57b81c473e479737"

    def install
      bin.install "seamlessloop"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Seamlessloop
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/schollz/seamlessloop/releases/download/v0.1.0/seamlessloop_0.1.0_Linux-64bit.tar.gz"
      sha256 "1b0e2711727e3ceb07e5ffb8767d126a89a221f64c2d61c79a8b0cb5bd993efb"

      def install
        bin.install "seamlessloop"
      end
    end
  end

  test do
    system "#{bin}/seamlessloop --version"
  end
end
