# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seamlessloop < Formula
  desc "seamlessloop is a tool to make seamless loops (requires sox)."
  homepage "https://schollz.com/software/seamlessloop/"
  version "0.1.1"

  on_macos do
    url "https://github.com/schollz/seamlessloop/releases/download/v0.1.1/seamlessloop_0.1.1_macOS-64bit.tar.gz"
    sha256 "89dec5d1e5b0c130277a6f65eaa57e3ca0f95d8ceb4fb2ae01a640f1cc2f5823"

    def install
      bin.install "seamlessloop"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Seamlessloop
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/schollz/seamlessloop/releases/download/v0.1.1/seamlessloop_0.1.1_Linux-64bit.tar.gz"
      sha256 "8183ef9cbed1f9b5c8344f347122261ce84b53448451026613560c751e2e8827"

      def install
        bin.install "seamlessloop"
      end
    end
  end

  test do
    system "#{bin}/seamlessloop --version"
  end
end
