# This file was generated by GoReleaser. DO NOT EDIT.
class Squirrel < Formula
  desc "squirrel downloads URLs to a SQLite database."
  homepage "https://schollz.com/software/squirrel/"
  url "https://github.com/schollz/squirrel/releases/download/v1.0.5/squirrel_1.0.5_macOS-64bit.tar.gz"
  version "1.0.5"
  sha256 "170285465c313a1561529e625a191c954fadeca6de228289ed9089655ad5a9d9"

  def install
    bin.install "squirrel"
  end

  test do
    system "#{bin}/squirrel --version"
  end
end
