# This file was generated by GoReleaser. DO NOT EDIT.
class Zget < Formula
  desc "zget is a tool that allows any two computers to simply and securely transfer files and folders."
  homepage "https://schollz.com/software/zget/"
  version "1.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/schollz/zget/releases/download/v1.1.2/zget_1.1.2_macOS-64bit.tar.gz"
    sha256 "6d8e01f5c1141aa43f35931acc3ed736396cc9c4fff8a25d7db177ab893ad466"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/schollz/zget/releases/download/v1.1.2/zget_1.1.2_Linux-64bit.tar.gz"
      sha256 "a57a1d681e066dbefc4cc744c60047d0a4b83a7c55e1611119689e24b156c52b"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/schollz/zget/releases/download/v1.1.2/zget_1.1.2_Linux-ARM64.tar.gz"
        sha256 "d05a53db37c34012c21b974307c72add4817c5c93da6813f9a4923855e8d656c"
      else
      end
    end
  end

  def install
    bin.install "zget"
  end

  test do
    system "#{bin}/zget --version"
  end
end
