# This file was generated by GoReleaser. DO NOT EDIT.
class Zget < Formula
  desc "zget is a tool that allows any two computers to simply and securely transfer files and folders."
  homepage "https://schollz.com/software/zget/"
  version "1.1.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/schollz/zget/releases/download/v1.1.6/zget_1.1.6_macOS-64bit.tar.gz"
    sha256 "8cd9a3315f06b6a5fbcbc01dd66d030ce7d6da5912f3287afca3e85651838992"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/schollz/zget/releases/download/v1.1.6/zget_1.1.6_Linux-64bit.tar.gz"
      sha256 "20a362937ebe86fd168fe0d9c4750a32348b7eedaad7e0fef670b80037115d7b"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/schollz/zget/releases/download/v1.1.6/zget_1.1.6_Linux-ARM64.tar.gz"
        sha256 "66de6c5ddaa72ec5c9e56b4ae02e2c832cc1a93d180addc2d476fe764c53d3d3"
      else
      end
    end
  end

  def install
    bin.install "zget"
  end

  test do
    system "#{bin}/zget --version"
  end
end
